name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
    - uses: docker/login-action@v2
    - with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # fetch from dockerhub
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # fetch from dockerhub
          
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build -t streamlit_docker:$(date +%s) .
      
    - name: Docker tag
      run:  docker tag streamlit_docker:$(date +%s) sneh3298/goesnex-fastapi:streamlit-docker-$(date +%s)
      
    - name: Docker push 
      run: docker push sneh3298/goesnex-fastapi:streamlit-docker-$(date +%s)
      
    
