name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3      
      name: Login to Docker Hub
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # fetch from dockerhub
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # fetch from dockerhub
          
    - name: git variables
      run: echo "{IMAGE_TAG}={$(date +%s)}" >> $GITHUB_ENV
      
    - name: Build the Docker image
      run: docker build -t streamlit_docker:${{ env.IMAGE_TAG }} .
      
    - name: List Docker Images 
      run: docker images
      
    - name: Docker tag
      run:  docker tag streamlit_docker:${{ env.IMAGE_TAG }} sneh3298/goesnex-fastapi:streamlit-docker-${{ env.IMAGE_TAG }}
      
    - name: Docker push 
      run: docker push sneh3298/goesnex-fastapi:streamlit-docker-${{ env.IMAGE_TAG }}
      
    
