name: Deploy to GCP VM

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: DAMG7250 	
  GCP_VM_INSTANCE_NAME: damg7250-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: DAMG7250
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: SSH into GCP VM
        uses: appleboy/ssh-action@master
        with:
          host: damg7250-2
          username: snehil_aryan7823
          password: ${{ secrets.VM_PASSWORD }}
          port: 22

      - name: Run Docker container
        run: |
          sudo docker ps
